# -*- coding: utf-8 -*-
"""
Compatibility shim — do not edit this file directly.

Canonical source:
    src/common_libs/edflib_fork_mld/edfreader_mld2.py

This file re-exports everything from the canonical location so that any
code which does:
    from edfreader_mld2 import EDFreader
(with the bids_shifter directory on sys.path) will transparently get the
shared implementation.
"""
import sys
import os

# bids_shifter/ -> StepC_BIDS_management/ -> natus_edf_tools/ -> src/
_src_root = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..")
)
if _src_root not in sys.path:
    sys.path.insert(0, _src_root)

from common_libs.edflib_fork_mld.edfreader_mld2 import *  # noqa: F401, F403, E402
from common_libs.edflib_fork_mld.edfreader_mld2 import EDFreader, EDFexception  # noqa: F401, E402
