# -*- coding: utf-8 -*-
"""
EDF Anonymizer (Header scrub + optional embedded annotation blanking)

Design goals:
- No legacy dependencies (no ahocorasick/tqdm/numpy)
- Safe defaults: scrub header patient/recording fields
- Optional: blank EDF+/BDF+ embedded TAL/annotations at the binary level
- Stream copy: preserves file structure and size

Notes:
- This module does NOT attempt "string replacement redaction" inside TAL.
  It is designed for the policy: blank all annotation content (PHI-safe).
- For EDF: 2 bytes/sample (int16). For BDF: 3 bytes/sample (24-bit).
"""

from __future__ import annotations

import os
import re
import logging
from dataclasses import dataclass
from typing import List, Optional, Tuple, Dict, Any


# -----------------------------
# Helpers / constants
# -----------------------------

EDF_FIXED_HEADER_BYTES = 256
SIG_HEADER_BYTES_PER_SIGNAL = 256

ANNOTATION_LABELS = {
    "EDF Annotations",
    "BDF Annotations",
    "EDF+ Annotations",
    "BDF+ Annotations",
}

# Known-safe system annotation strings generated by Natus/Xltek amplifiers.
# These appear verbatim in every recording and contain no patient information.
# Any annotation text NOT in this set is treated as a potential PHI finding.
NATUS_SYSTEM_ANNOTATION_ALLOWLIST: frozenset = frozenset({
    "Montage Event",
    "Start Recording",
    "Clip Note",
    "Video Recording ON",
    "Video Recording OFF",
    "Impedance Check",
    "Impedance Measurement",
    "DC Offset Correction",
    "Amplifier Disconnect",
    "Amplifier Connect",
    "File Created",
    "File Closed",
    "Seizure Begin",
    "Seizure End",
    "Seizure",
})


def _setup_logger(log_dir: Optional[str] = None) -> logging.Logger:
    logger = logging.getLogger("edf_anonymizer")
    if logger.handlers:
        return logger

    logger.setLevel(logging.INFO)
    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO)
    ch.setFormatter(logging.Formatter("%(levelname)s: %(message)s"))
    logger.addHandler(ch)

    if log_dir:
        os.makedirs(log_dir, exist_ok=True)
        fh = logging.FileHandler(os.path.join(log_dir, "edf_anonymizer.log"), encoding="utf-8")
        fh.setLevel(logging.INFO)
        fh.setFormatter(logging.Formatter("%(asctime)s - %(levelname)s - %(message)s"))
        logger.addHandler(fh)

    return logger


def _padtrim_ascii(text: str, length: int) -> bytes:
    b = (text or "").encode("ascii", errors="ignore")[:length]
    return b + (b" " * (length - len(b)))


def _safe_int_from_ascii(field_bytes: bytes) -> Optional[int]:
    s = field_bytes.decode("ascii", errors="ignore").strip()
    if not s:
        return None
    try:
        return int(s)
    except ValueError:
        return None


def _safe_float_from_ascii(field_bytes: bytes) -> Optional[float]:
    s = field_bytes.decode("ascii", errors="ignore").strip()
    if not s:
        return None
    try:
        return float(s)
    except ValueError:
        return None


def _looks_like_bdf(path: str, header_reserved: bytes) -> bool:
    ext = os.path.splitext(path)[1].lower()
    if ext == ".bdf":
        return True
    r = header_reserved.decode("ascii", errors="ignore").upper()
    if "BDF" in r or "24BIT" in r or "24-BIT" in r:
        return True
    return False


@dataclass
class EDFStructure:
    header_bytes: int
    n_signals: int
    n_records: Optional[int]
    record_duration: Optional[float]
    bytes_per_sample: int
    samples_per_signal: List[int]
    labels: List[str]

    @property
    def record_bytes(self) -> int:
        return sum(self.samples_per_signal) * self.bytes_per_sample

    def annotation_signal_indices(self) -> List[int]:
        out = []
        for i, lbl in enumerate(self.labels):
            if lbl.strip() in ANNOTATION_LABELS:
                out.append(i)
        return out

    def annotation_segments(self) -> List[Tuple[int, int]]:
        segs: List[Tuple[int, int]] = []
        offset = 0
        for i, n_samp in enumerate(self.samples_per_signal):
            size = n_samp * self.bytes_per_sample
            if self.labels[i].strip() in ANNOTATION_LABELS:
                segs.append((offset, size))
            offset += size
        return segs


def parse_edf_structure(file_path: str, logger: Optional[logging.Logger] = None) -> EDFStructure:
    logger = logger or _setup_logger(None)

    with open(file_path, "rb") as f:
        fixed = f.read(EDF_FIXED_HEADER_BYTES)
        if len(fixed) != EDF_FIXED_HEADER_BYTES:
            raise ValueError(f"Not a valid EDF/BDF file (header too short): {file_path}")

        header_bytes = _safe_int_from_ascii(fixed[184:192])
        n_records = _safe_int_from_ascii(fixed[236:244])
        record_duration = _safe_float_from_ascii(fixed[244:252])
        n_signals = _safe_int_from_ascii(fixed[252:256])

        if header_bytes is None or n_signals is None:
            raise ValueError(f"Cannot parse EDF header_bytes or n_signals: {file_path}")

        reserved = fixed[192:236]
        bytes_per_sample = 3 if _looks_like_bdf(file_path, reserved) else 2

        f.seek(0)
        header = f.read(header_bytes)
        if len(header) != header_bytes:
            raise ValueError(f"Header truncated: expected {header_bytes}, got {len(header)}")

        base = EDF_FIXED_HEADER_BYTES
        ns = n_signals

        def read_field(field_len: int) -> List[bytes]:
            nonlocal base
            chunk = header[base: base + field_len * ns]
            base += field_len * ns
            return [chunk[i * field_len:(i + 1) * field_len] for i in range(ns)]

        labels_b = read_field(16)
        _ = read_field(80)  # transducer
        _ = read_field(8)   # physdim
        _ = read_field(8)   # physmin
        _ = read_field(8)   # physmax
        _ = read_field(8)   # digmin
        _ = read_field(8)   # digmax
        _ = read_field(80)  # prefilter
        samples_b = read_field(8)
        _ = read_field(32)  # reserved

        labels = [b.decode("ascii", errors="ignore").strip() for b in labels_b]
        samples_per_signal: List[int] = []
        for sb in samples_b:
            v = _safe_int_from_ascii(sb)
            samples_per_signal.append(v if v is not None else 0)

        return EDFStructure(
            header_bytes=header_bytes,
            n_signals=ns,
            n_records=n_records,
            record_duration=record_duration,
            bytes_per_sample=bytes_per_sample,
            samples_per_signal=samples_per_signal,
            labels=labels,
        )


# -----------------------------
# Header scrub
# -----------------------------

def scrub_header_bytes(
    header: bytes,
    patient_field: str = "X X X X",
    recording_field: str = "Startdate X X X X",
) -> bytes:
    if len(header) < EDF_FIXED_HEADER_BYTES:
        raise ValueError("Header buffer too short.")
    out = bytearray(header)
    out[8:88] = _padtrim_ascii(patient_field, 80)
    out[88:168] = _padtrim_ascii(recording_field, 80)
    return bytes(out)


def scrub_header_in_place(
    edf_path: str,
    patient_field: str = "X X X X",
    recording_field: str = "Startdate X X X X",
) -> None:
    """
    Scrub patient/recording header fields in-place.
    Does NOT modify annotations (data records).
    """
    logger = _setup_logger(None)
    with open(edf_path, "r+b") as f:
        fixed = f.read(EDF_FIXED_HEADER_BYTES)
        if len(fixed) != EDF_FIXED_HEADER_BYTES:
            raise ValueError(f"Not a valid EDF/BDF (header too short): {edf_path}")
        header_bytes = _safe_int_from_ascii(fixed[184:192])
        if header_bytes is None:
            raise ValueError(f"Cannot parse header length: {edf_path}")
        f.seek(0)
        header = f.read(header_bytes)
        if len(header) != header_bytes:
            raise ValueError(f"Header truncated: {edf_path}")
        new_header = scrub_header_bytes(header, patient_field=patient_field, recording_field=recording_field)
        f.seek(0)
        f.write(new_header)
    logger.info(f"Scrubbed EDF/BDF header in-place: {edf_path}")


# -----------------------------
# Full-file anonymization
# -----------------------------

def _blank_tal_annotations(chunk: bytearray, off: int, sz: int) -> None:
    """
    Blank annotation text within a TAL block while preserving timing structure.
    Replaces annotation text (after 0x14 separators) with spaces,
    keeping timestamps and structural bytes intact.
    """
    end = off + sz
    pos = off
    data = chunk

    while pos < end:
        if data[pos] in (ord('+'), ord('-')):
            sep1 = data.find(0x14, pos, end)
            if sep1 == -1:
                break
            null_pos = data.find(0x00, sep1, end)
            if null_pos == -1:
                null_pos = end
            cursor = sep1 + 1
            while cursor < null_pos:
                next_sep = data.find(0x14, cursor, null_pos)
                if next_sep == -1:
                    for i in range(cursor, null_pos):
                        data[i] = ord(' ')
                    break
                else:
                    for i in range(cursor, next_sep):
                        data[i] = ord(' ')
                    cursor = next_sep + 1
            pos = null_pos + 1
        else:
            pos += 1


def anonymize_edf_file(
    src_path: str,
    dst_path: str,
    *,
    patient_field: str = "X X X X",
    recording_field: str = "Startdate X X X X",
    blank_annotations: bool = True,
    buffer_mb: int = 64,
    log_dir: Optional[str] = None,
) -> bool:
    """
    Copy src EDF/BDF to dst with anonymized header, and optionally blank embedded annotations.
    Returns True on success, False on failure.
    """
    logger = _setup_logger(log_dir)

    try:
        st = parse_edf_structure(src_path, logger=logger)
        header_bytes = st.header_bytes
        record_bytes = st.record_bytes
        annot_segs = st.annotation_segments() if blank_annotations else []

        if record_bytes <= 0:
            raise ValueError(f"Computed record_bytes <= 0 (bad header?): {src_path}")

        with open(src_path, "rb") as fin, open(dst_path, "wb") as fout:
            header = fin.read(header_bytes)
            if len(header) != header_bytes:
                raise ValueError(f"Header truncated: {src_path}")
            fout.write(scrub_header_bytes(header, patient_field=patient_field, recording_field=recording_field))

            rec_count = 0
            while True:
                chunk = fin.read(record_bytes)
                if not chunk:
                    break
                if len(chunk) != record_bytes:
                    fout.write(chunk)
                    break
                if annot_segs:
                    b = bytearray(chunk)
                    for off, sz in annot_segs:
                        if sz <= 0:
                            continue
                        if off + sz <= len(b):
                            _blank_tal_annotations(b, off, sz)
                    fout.write(bytes(b))
                else:
                    fout.write(chunk)
                rec_count += 1

        src_sz = os.path.getsize(src_path)
        dst_sz = os.path.getsize(dst_path)
        if src_sz != dst_sz:
            logger.warning(f"Size mismatch: src={src_sz} dst={dst_sz} ({src_path})")

        logger.info(
            f"Anonymized: {os.path.basename(src_path)} -> {os.path.basename(dst_path)} "
            f"(records={rec_count}, blank_annotations={blank_annotations})"
        )
        return True

    except Exception as e:
        logger.error(f"Anonymization failed for {src_path}: {e}")
        return False


# -----------------------------
# Verification
# -----------------------------

def _extract_tal_content(seg: bytes, max_tals: int = 20, max_text_len: int = 80) -> List[Dict[str, Any]]:
    """
    Parse TAL bytes from one annotation channel segment.
    Returns list of {"onset": str, "texts": [str, ...]} dicts.
    """
    entries: List[Dict[str, Any]] = []
    end = len(seg)
    pos = 0
    while pos < end and len(entries) < max_tals:
        if seg[pos] not in (ord('+'), ord('-')):
            pos += 1
            continue
        sep1 = seg.find(0x14, pos)
        if sep1 == -1:
            break
        onset = seg[pos:sep1].decode('ascii', errors='replace').strip()
        null_pos = seg.find(0x00, sep1)
        if null_pos == -1:
            null_pos = end
        texts: List[str] = []
        cursor = sep1 + 1
        while cursor < null_pos:
            next_sep = seg.find(0x14, cursor, null_pos)
            chunk_end = next_sep if next_sep != -1 else null_pos
            text = seg[cursor:chunk_end].decode('utf-8', errors='replace').strip()
            if text:
                texts.append(text[:max_text_len])
            cursor = (next_sep + 1) if next_sep != -1 else null_pos
        if onset:
            entries.append({"onset": onset, "texts": texts})
        pos = null_pos + 1
    return entries


def verify_edf_anonymized(
    edf_path: str,
    *,
    expected_patient_field: str = "X X X X",
    expected_recording_field_prefix: str = "Startdate",
    require_blank_annotations: bool = False,
    max_records_to_check: int = 3,
    annotation_allowlist: Optional[frozenset] = NATUS_SYSTEM_ANNOTATION_ALLOWLIST,
) -> Dict[str, Any]:
    """
    Verify whether patient/recording header fields are scrubbed and whether
    annotation channel content is free of unrecognised text.

    annotation_allowlist: strings considered safe system annotations (not PHI).
    Any text NOT in the allowlist triggers annotations_blank_ok=False.
    Pass annotation_allowlist=frozenset() for strict mode (any text = fail).
    Default: NATUS_SYSTEM_ANNOTATION_ALLOWLIST.

    Always-populated fields:
      header_patient_ok, header_recording_ok, header_ok
      annotation_channels_present
      n_signals, n_annotation_channels, annotation_channel_labels
      n_records, record_duration_s

    Populated when require_blank_annotations=True:
      annotations_blank_ok        - True if no unrecognised text found
      n_records_checked
      n_records_with_phi          - records with unrecognised (non-allowlisted) text
      non_blank_byte_count        - total char count of unrecognised text
      first_failing_record
      annotation_content_sample   - TAL dicts from first failing record
      allowlisted_texts_found     - safe system strings seen (informational)
      unknown_texts_found         - unrecognised strings found (potential PHI)
    """
    logger = _setup_logger(None)

    result: Dict[str, Any] = {
        "path": os.path.abspath(edf_path),
        "header_patient_ok": False,
        "header_recording_ok": False,
        "header_ok": False,
        "annotation_channels_present": False,
        "annotations_blank_ok": None,
        "n_signals": None,
        "n_annotation_channels": None,
        "annotation_channel_labels": [],
        "n_records": None,
        "record_duration_s": None,
        "n_records_checked": None,
        "n_records_with_phi": None,
        "non_blank_byte_count": None,
        "first_failing_record": None,
        "annotation_content_sample": None,
        "allowlisted_texts_found": None,
        "unknown_texts_found": None,
        "notes": [],
    }

    try:
        st = parse_edf_structure(edf_path, logger=logger)
        annot_segs = st.annotation_segments()
        annot_indices = st.annotation_signal_indices()
        annot_labels = [st.labels[i] for i in annot_indices]

        result["annotation_channels_present"] = len(annot_segs) > 0
        result["n_signals"] = st.n_signals
        result["n_annotation_channels"] = len(annot_indices)
        result["annotation_channel_labels"] = annot_labels
        result["n_records"] = st.n_records
        result["record_duration_s"] = st.record_duration

        with open(edf_path, "rb") as f:
            fixed = f.read(EDF_FIXED_HEADER_BYTES)
            if len(fixed) != EDF_FIXED_HEADER_BYTES:
                result["notes"].append("Header too short.")
                return result

            patient = fixed[8:88].decode("ascii", errors="ignore").strip()
            rec = fixed[88:168].decode("ascii", errors="ignore").strip()

            result["header_patient_ok"] = (patient == expected_patient_field)
            result["header_recording_ok"] = rec.startswith(expected_recording_field_prefix)
            result["header_ok"] = result["header_patient_ok"] and result["header_recording_ok"]

            if not require_blank_annotations:
                return result

            if not annot_segs:
                result["annotations_blank_ok"] = True
                result["n_records_checked"] = 0
                result["n_records_with_phi"] = 0
                result["non_blank_byte_count"] = 0
                result["allowlisted_texts_found"] = []
                result["unknown_texts_found"] = []
                result["notes"].append("No annotation channels detected.")
                return result

            allowlist = annotation_allowlist if annotation_allowlist is not None else frozenset()
            rec_bytes = st.record_bytes

            f.seek(st.header_bytes)
            ok = True
            records_checked = 0
            records_with_phi = 0
            total_unknown_chars = 0
            first_failing: Optional[int] = None
            all_allowlisted: set = set()
            all_unknown: set = set()

            for rec_idx in range(max_records_to_check):
                recbuf = f.read(rec_bytes)
                if not recbuf or len(recbuf) != rec_bytes:
                    break

                records_checked += 1
                record_has_phi = False

                for off, sz in annot_segs:
                    for tal in _extract_tal_content(recbuf[off:off + sz]):
                        for text in tal["texts"]:
                            if not text:
                                continue
                            if text in allowlist:
                                all_allowlisted.add(text)
                            else:
                                all_unknown.add(text)
                                total_unknown_chars += len(text)
                                record_has_phi = True

                if record_has_phi:
                    records_with_phi += 1
                    ok = False
                    if first_failing is None:
                        first_failing = rec_idx
                        sample: List[Dict[str, Any]] = []
                        for off2, sz2 in annot_segs:
                            sample.extend(_extract_tal_content(recbuf[off2:off2 + sz2]))
                        result["annotation_content_sample"] = sample

            result["annotations_blank_ok"] = ok
            result["n_records_checked"] = records_checked
            result["n_records_with_phi"] = records_with_phi
            result["non_blank_byte_count"] = total_unknown_chars
            result["first_failing_record"] = first_failing
            result["allowlisted_texts_found"] = sorted(all_allowlisted)
            result["unknown_texts_found"] = sorted(all_unknown)

        return result

    except Exception as e:
        result["notes"].append(f"verify exception: {e}")
        return result
